// 公共
const COM_LOADING_STATUS = 'COM_LOADING_STATUS'
// user 用户
const SET_USER_INFO = 'SETUSERINFO' // 设置用户信息
const SET_TOKEN = 'SET_TOKEN' // 设置token
const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS' // 设置登录状态
const SET_USER_DATA = 'SET_USER_DATA' // 获取用户数据信息

const SET_THUMB_STATUS = 'SET_THUMB_STATUS' // 设置用户点赞
export {COM_LOADING_STATUS, SET_USER_INFO, SET_TOKEN, SET_LOGIN_STATUS, SET_USER_DATA, SET_THUMB_STATUS}
