// 公共
const COM_LOADING_STATUS = 'COM_LOADING_STATUS'
// user 用户
const SET_USER_INFO = 'SET_USER_INFO' // 设置用户信息
const UPDATE_USER_INFO = 'UPDATE_USER_INFO' // 设置登录状态
const SET_TOKEN = 'SET_TOKEN' // 设置token
const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS' // 设置登录状态
const SET_FOLLOWTOPIC_STATUS = 'SET_FOLLOWTOPIC_STATUS' // 设置登录状态

export {COM_LOADING_STATUS, SET_USER_INFO, UPDATE_USER_INFO, SET_TOKEN, SET_LOGIN_STATUS, SET_FOLLOWTOPIC_STATUS}
